
# futility monitoring for interim and final analysis
todo3_futility <- function(ia12, fdata, ia.post, fa.post1, fa.post2, fa.post3, post1, post2,
                           ntrial, peff, theta0, m1, nsample){
  
  SEL <- matrix(0,ncol=length(peff),nrow=ntrial)  
  FUTILE <- array(1,c(2,length(peff),ntrial))
  inconclusive <- matrix(1,ncol=length(peff),nrow=ntrial)
  
  ## all posible cutoff combinations for futility monitoring
  gamma1 <- log(seq(1,0.5, by = -0.025))/log(0.5)
  lambda1 <- seq(0.5,1, by = 0.0025)
  a12 <- NULL
  for(ia1 in 1:length(lambda1)){ for(ia2 in 1:length(gamma1)){a12 <- rbind(a12,c(lambda1[ia1],gamma1[ia2]))} }
  a1 <- a12[ia12,1]*(m1/nsample)^a12[ia12,2]
  a2 <- a12[ia12,1]
  
  ## isotonic regression
  pava <- function (x, wt = rep(1, length(x))){
    n <- length(x)
    if (n <= 1)
      return(x)
    if (any(is.na(x)) || any(is.na(wt))) {
      stop("Missing values in 'x' or 'wt' not allowed")
    }
    lvlsets <- (1:n)
    repeat {
      viol <- (as.vector(diff(x)) < 0)
      if (!(any(viol)))
        break
      i <- min((1:(n - 1))[viol])
      lvl1 <- lvlsets[i]
      lvl2 <- lvlsets[i + 1]
      ilvl <- (lvlsets == lvl1 | lvlsets == lvl2)
      x[ilvl] <- sum(x[ilvl] * wt[ilvl])/sum(wt[ilvl])
      lvlsets[ilvl] <- lvl1
    }
    x
  }
  
  ## making desicions for the simulated trials generated by function 'todo3_data_generation()'
  for(trial in 1:ntrial){
    
    ## interim analysis
    ia.post[trial,] <- pava(ia.post[trial,],1/c(fdata[1,2,trial],fdata[2,2,trial],fdata[3,2,trial])) 
    setI <- which(ia.post[trial,]>=a1)     ## doses passed the interim futility monitoring
    exclude <- which(ia.post[trial,]<a1)   ## doses failed to pass the interim futility monitoring
    FUTILE[1,setI,trial] <- 0
    if(length(exclude)>0){
      inconclusive[trial,exclude] <- -2
      fdata[exclude,3:4,trial] <- 0
      fdata[exclude,5:6,trial] <- fdata[exclude,1:2,trial]
    }
    if(length(exclude)==length(peff)){next}
    
    ## final analysis
    setII <- setI
    fa.post1[trial,] <- pava(fa.post1[trial,],1/c(fdata[1,6,trial],fdata[2,6,trial],fdata[3,6,trial]))
    fa.post3[trial,] <- pava(fa.post3[trial,],1/c(fdata[1,2,trial],fdata[2,6,trial],fdata[3,6,trial]))
    fa.post2[trial,] <- pava(fa.post2[trial,],1/c(fdata[1,2,trial],fdata[2,2,trial],fdata[3,6,trial])) 
    
    if(length(setI)==3){
      ## if all 3 doses pass the interim futility monitoring
      setII <- which(ia.post[trial,]>=a1 & fa.post1[trial,]>=a2)  ## doses passed the final futility monitoring
      exclude <- which(ia.post[trial,]<a1 | fa.post1[trial,]<a2)  ## doses failed to pass the final futility monitoring
      
    }else if(length(setI)==2){
      ## if doses 2 and 3 pass the interim futility monitoring
      if(fa.post3[trial,3]<a2){ setII <- NULL;exclude <- 1:3 
      }else if(fa.post3[trial,2]<a2){ setII <- 3;exclude <- 1:2}
      
    }else{
      ## if only dose 3 pass the interim futility monitoring
      if(fa.post2[trial,3]<a2){ setII <- NULL;exclude <- 1:3 } }
    
    
    FUTILE[2,setII,trial] <- 0
    if(length(exclude)>0){inconclusive[trial,exclude] <- -2}
    
  }
  
  pts <- apply(fdata,c(1,2),mean)
  
  futile <- apply(FUTILE,c(1,2), mean)*100
  sel <- c(colMeans(SEL),1-sum(colMeans(SEL)))
  
  none <- sum(colSums(FUTILE[2,,])==3)*100/ntrial
  overallpower <- 0
  for(trial in 1:ntrial){
    if( sum(FUTILE[2,,trial]==(peff<=theta0))==length(peff) ){overallpower <- overallpower + 100/ntrial}
  }
  
  result.list <- list(peff=peff, pts=round(pts,2), 
                      parameter=c(a1 = a1, a2 = a2, lambda1 = a12[ia12,1], gamma1 = a12[ia12,2]), 
                      overallpower=overallpower)
  return(result.list)
}