
# futility monitoring and dose comparison for interim and final analysis
todo3 <- function(ic12, fdata, ia.post, fa.post1, fa.post2, fa.post3, 
                  ia.mean, fa.mean1, fa.mean2, fa.mean3, post1, post2,
                  ntrial, peff, theta0, delta1, ia12, idr.m, wl, m1, nsample){
  
  library(rjags)
  
  SEL <- matrix(0,ncol=length(peff),nrow=ntrial)  
  fa.mean <- matrix(0,ncol=length(peff),nrow=ntrial)
  FUTILE <- array(1,c(2,length(peff),ntrial))
  inconclusive <- matrix(1,ncol=length(peff),nrow=ntrial)
  
  ## all posible cutoff combinations for futility monitoring
  gamma1 <- log(seq(1,0.5, by = -0.025))/log(0.5)
  lambda1 <- seq(0.5,1, by = 0.0025)
  a12 <- NULL
  for(ia1 in 1:length(lambda1)){ for(ia2 in 1:length(gamma1)){a12 <- rbind(a12,c(lambda1[ia1],gamma1[ia2]))} }
  a1 <- a12[ia12,1]*(m1/nsample)^a12[ia12,2]
  a2 <- a12[ia12,1]
  
  ## all posible cutoff combinations for non-inferior comparison
  c12 <- NULL
  for(ic1 in 1:98){
    for(ic2 in (ic1):min(ic1+60,99)){c12 <- rbind(c12,c(ic1,ic2)/100)} }
  c1 <- c12[ic12,1];c2 <- c12[ic12,2]
  
  ## isotonic regression
  pava <- function (x, wt = rep(1, length(x))){
    n <- length(x)
    if (n <= 1)
      return(x)
    if (any(is.na(x)) || any(is.na(wt))) {
      stop("Missing values in 'x' or 'wt' not allowed")
    }
    lvlsets <- (1:n)
    repeat {
      viol <- (as.vector(diff(x)) < 0)
      if (!(any(viol)))
        break
      i <- min((1:(n - 1))[viol])
      lvl1 <- lvlsets[i]
      lvl2 <- lvlsets[i + 1]
      ilvl <- (lvlsets == lvl1 | lvlsets == lvl2)
      x[ilvl] <- sum(x[ilvl] * wt[ilvl])/sum(wt[ilvl])
      lvlsets[ilvl] <- lvl1
    }
    x
  }
  
  ## making desicions for the simulated trials generated by function 'todo3_data_generation()'
  for(trial in 1:ntrial){
    
    ## interim analysis
    ia.post[trial,] <- pava(ia.post[trial,],1/c(fdata[1,2,trial],fdata[2,2,trial],fdata[3,2,trial])) 
    setI <- which(ia.post[trial,]>=a1)     ## doses passed the interim futility monitoring
    exclude <- which(ia.post[trial,]<a1)   ## doses failed to pass the interim futility monitoring
    FUTILE[1,setI,trial] <- 0
    if(length(exclude)>0){
      inconclusive[trial,exclude] <- -2
      fdata[exclude,3:4,trial] <- 0
      fdata[exclude,5:6,trial] <- fdata[exclude,1:2,trial]
    }
    if(length(exclude)==length(peff)){
      fa.mean[trial,] <- ia.mean[trial,]
      next}
    
    ## final analysis
    setII <- setI
    fa.post1[trial,] <- pava(fa.post1[trial,],1/c(fdata[1,6,trial],fdata[2,6,trial],fdata[3,6,trial]))
    fa.post3[trial,] <- pava(fa.post3[trial,],1/c(fdata[1,2,trial],fdata[2,6,trial],fdata[3,6,trial]))
    fa.post2[trial,] <- pava(fa.post2[trial,],1/c(fdata[1,2,trial],fdata[2,2,trial],fdata[3,6,trial])) 
    
    if(length(setI)==3){
      ## if all 3 doses pass the interim futility monitoring
      fa.mean[trial,] <- fa.mean1[trial,]
      setII <- which(ia.post[trial,]>=a1 & fa.post1[trial,]>=a2)  ## doses passed the final futility monitoring
      exclude <- which(ia.post[trial,]<a1 | fa.post1[trial,]<a2)  ## doses failed to pass the final futility monitoring
      
    }else if(length(setI)==2){
      ## if doses 2 and 3 pass the interim futility monitoring
      fa.mean[trial,] <- fa.mean3[trial,]
      if(fa.post3[trial,3]<a2){ setII <- NULL;exclude <- 1:3 
      }else if(fa.post3[trial,2]<a2){ setII <- 3;exclude <- 1:2}
      
    }else{
      ## if only dose 3 pass the interim futility monitoring
      fa.mean[trial,] <- fa.mean2[trial,]
      if(fa.post2[trial,3]<a2){ setII <- NULL;exclude <- 1:3 } }
    
    
    FUTILE[2,setII,trial] <- 0
    if(length(exclude)>0){inconclusive[trial,exclude] <- -2}
    if(length(exclude)==length(peff)){next}
    
    # dose comparison
    post2[trial,] <- pava(post2[trial,],1/c(fdata[3,6,trial]+fdata[1,2,trial],fdata[3,6,trial]+fdata[2,6,trial]))
    post1[trial,] <- pava(post1[trial,],1/c(fdata[3,6,trial]+fdata[1,6,trial],fdata[3,6,trial]+fdata[2,6,trial]))
    
    if(length(setII)==1){
      ## if only dose 3 pass the final futility monitoring
      SEL[trial,setII] <- SEL[trial,setII] + 1
      
    }else if(length(setII)==2){ ## if doses 2 and 3 pass the final futility monitoring
      
      ## if all doses pass the interim futility monitoring
      if(length(setI)==3){
        if(post1[trial,2]<=c1){ # inferior
          inconclusive[trial,setII[1]] <- 0
          SEL[trial,3] <- SEL[trial,3] + 1
        }else if(post1[trial,2]>c1 & post1[trial,2]<c2){ # inconclusive
          inconclusive[trial,setII[1]] <- -1
        }else{ # non-inferior
          SEL[trial,2] <- SEL[trial,2] + 1 }
      }
      
      ## if only doses 2 and 3 pass the interim futility monitoring
      if(length(setI)==2){
        if(post2[trial,2]<c1){ # inferior
          inconclusive[trial,setII[1]] <- 0
          SEL[trial,3] <- SEL[trial,3] + 1
        }else if(post2[trial,2]>c1 & post2[trial,2]<c2){ # inconclusive
          inconclusive[trial,setII[1]] <- -1
        }else{ # non-inferior
          SEL[trial,2] <- SEL[trial,2] + 1 }
      }
    }else{
      ## if all doses pass the final futility monitoring
      for(i in 1:(length(setII)-1)){
        if(post1[trial,i]<c1){ # inferior
          inconclusive[trial,setII[i]] <- 0
        }else if(post1[trial,i]>c1 & post1[trial,i]<c2){ # inconclusive
          inconclusive[trial,setII[i]] <- -1
        }
      }
      # make decision
      if(inconclusive[trial,1]==0 & inconclusive[trial,2]==0){ SEL[trial,3] <- SEL[trial,3] + 1 } 
      if(inconclusive[trial,1]==0 & inconclusive[trial,2]==1){ SEL[trial,2] <- SEL[trial,2] + 1 } 
      if(inconclusive[trial,1]==1 & inconclusive[trial,2]==1){ SEL[trial,1] <- SEL[trial,1] + 1 } 
    }
  }
  
  pts <- apply(fdata,c(1,2),mean)
  futile <- apply(FUTILE,c(1,2), mean)*100
  sel <- c(colMeans(SEL),1-sum(colMeans(SEL)))
  
  none <- sum(colSums(FUTILE[2,,])==3)*100/ntrial
  overallpower <- 0
  for(trial in 1:ntrial){
    if( sum(FUTILE[2,,trial]==(peff<=theta0))==length(peff) ){overallpower <- overallpower + 100/ntrial}
  }
  
  inc.d2 <- (sum(inconclusive[,1]==0 & inconclusive[,2]==-1)+sum(inconclusive[,1]==-2 & inconclusive[,2]==-1))*100/ntrial
  inc.d1d2 <- sum(inconclusive[,1]==-1 & inconclusive[,2]==-1)*100/ntrial
  inc.d1 <- sum(inconclusive[,1]==-1 & inconclusive[,2]==1)*100/ntrial
  inc <- c(inc.d1d2,inc.d1,inc.d2)
  
  present0 <- c(sel[1:length(peff)]*100,sum(inc),futile[2,length(peff)],pts[,6])
  DIDR <- sum(present0*idr.m)
  weighted_loss <- sum(inc)*wl+DIDR
  if(sum(peff<=theta0)==length(peff)){weighted_loss <- DIDR}
  present <- c(sel[1:length(peff)]*100, sum(inc), DIDR, weighted_loss, pts[,6], 100-futile[2,1], 100-futile[2,2], 100-futile[2,3], none)
  present <- t(as.matrix(present))
  colnames(present) <- c('sel1','sel2','sel3','SIR','IDR','WL','ASS1','ASS2','ASS3','go1','go2','go3','none')
  
  parameter <- c(m1, nsample, a12[ia12,1], a12[ia12,2], c1, c2)
  parameter <- t(as.matrix(parameter))
  colnames(parameter) <- c('m1', 'n', 'lambda', 'gamma', 'c1', 'c2')
  
  ## bias and MSE
  bias <- mse <- rep(0, length(peff))
  for(id in 1:length(peff)){
    bias[id] <- mean(fa.mean[,id] - peff[id])
    mse[id] <- mean((fa.mean[,id] - peff[id])^2)
  }
  
  result.list <- list(peff = peff, parameter = parameter,
                      present = present, bias = bias, mse = mse)
  return(result.list)
}